# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_caso', models.CharField(max_length=50, unique=True, verbose_name='Nro Caso')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción')),
                ('solicitante_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Solicitante')),
                ('solicitante_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Solicitante')),
                ('beneficiario_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beneficiario')),
                ('beneficiario_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Beneficiario')),
                ('tipo_solicitud', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Solicitud')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
                ('descripcion_caso', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('atendido_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atendido Por')),
                ('estatus', models.CharField(default='PENDIENTE', max_length=100, verbose_name='Estatus')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Monto USD')),
                ('monto_bs', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True, verbose_name='Monto Bs')),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tasa BCV')),
                ('partida', models.CharField(blank=True, max_length=150, null=True, verbose_name='Partida')),
                ('mes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mes')),
                ('score_prioridad', models.IntegerField(default=0, verbose_name='Score Riesgo')),
                ('nivel_prioridad', models.CharField(default='BAJO', max_length=20, verbose_name='Nivel')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud GRS',
                'verbose_name_plural': 'Solicitudes GRS',
            },
        ),
    ]
