# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_social', '0002_solicitud_notas_asignado_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado de Venezuela donde se atiende el caso.', max_length=100, null=True, verbose_name='Estado (entidad federal)'),
        ),
    ]
