# Generated by Django 5.2.12 on 2026-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_social', '0003_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='monto_bs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Monto Bs'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tasa_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Tasa BCV'),
        ),
    ]
